# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'recipeResearcher' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire','~> 5.4'
  pod 'SwiftyJSON'
  # Pods for recipeResearcher

  target 'recipeResearcherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'recipeResearcherUITests' do
    # Pods for testing
  end

end
